[package]
name = "jsx_types"
version = "0.1.0"
authors = ["Robert <robert.balicki@gmail.com>"]

[dependencies]
# enum_derive = "0.1.7"
# custom_derive = "0.1.7"
wasm-bindgen = "0.2"
serde = "1.0.62"
serde_json = "1.0.18"
serde_derive = "1.0.62"
