[package]
name = "jsx_macro"
version = "0.1.0"
authors = ["Robert <robert.balicki@gmail.com>"]

[dependencies]
jsx_types = { path = "../jsx_types" }
proc-macro2 = "0.4"
quote = "0.6.3"

[lib]
proc-macro = true
