[package]
name = "jsx_macro"
version = "0.1.0"
authors = ["Robert <robert.balicki@gmail.com>"]

[dependencies]
jsx_types = { path = "../jsx_types" }
proc-macro2 = { path = "../proc-macro2", features = ["nightly"] }
quote = { path = "../quote" }
nom = "4.0.0"

[lib]
proc-macro = true
