[package]
name = "jsx_macro_tests"
version = "0.1.0"
authors = ["Robert <robert.balicki@gmail.com>"]

[dependencies]
jsx_macro = { path = "../jsx_macro" }
jsx_types = { path = "../jsx_types" }
compiletest_rs = "*"
